

{% block content %}
<div class="container">

<h1>Admin dashboard</h1>
<?php 
/**
 * How many users are there?
 */ 
$users = Users::find();
echo "Number of users in database: ", count($users), "\n";

/**
 * Get and print virtual users ordered by name
 */ 
$users = Users::find(array(

    "order" => "first_usr"
));
?>
<table><tr><th>First Name</th><th>Email</th><th></th></tr>
<?php
foreach ($users as $user) {
	if ( "admin@admin.com" == $user->email_usr ) continue;
    echo "<tr><td>", $user->first_usr, "</td><td>", $user->email_usr, "</td>";
    echo "<td>";
    echo $this->tag->linkTo(array('admin/edit/user/'. $user->id_usr . '/', 'Edit', 'class' => 'button'));

    echo "</td></tr>";
}
?>
</table>


	<h2>Add new user with this form:</h2>
	{{ form("admin/register", 'id': 'registerForm', 'onbeforesubmit': 'return false') }}
		<div>
		<label for='name'>First Name</label>
			{{ text_field("name") }}
			<p class="alert" id="name_alert"> Please enter the user's first name.</p>
		</div>
		<div>
		<label for='email'>E-Mail</label>
			{{ text_field("email") }}
			<p class="alert" id="email_alert"> Please enter the user's valid e-mail.</p>
		</div>

		<label for='password'>Password</label>	
			{{ text_field("password", "value" : "password") }}
			<p class="alert" id="email_alert"> Please enter the user's password.</p>

		<div> 
		 {{ submit_button("Enter") }} 
		</div>
	{{ endform() }}
</div>
{% endblock %}