


	{{ partial('layouts/member') }}
<div class="container">

    <p>Your Project Information</p>
    
    
    <ul class="app-listings">
    <?php echo "<p>You created ". count($apps) ." apps:</p>" ; ?>
    {% for app in apps %}
        <li>
		<div class="icon">
        <img src={{ app.icon_app }} />
		</div>
        <h2>{{ app.name_app }}</h2>
        <p>{{ app.tagline_app }}</p>
        <p>{{ app.creator_app_usr }}</p>
        
        <p>{{ user }}</p>
        <p data-desc={{ app.desc_app }}></p>
        <span>Votes:</span>
        </li>
    {% endfor %}

    </ul>
        
</div>
