<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {{ get_title() }}
        {{ stylesheet_link('css/normalize.css') }}
        {{ stylesheet_link('css/skeleton.css') }}
        
        {{ stylesheet_link('css/style.css') }}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Apps.BePlace">
        <meta name="author" content="Chris Craven">
        {{ javascript_include('https:/**
 * 
 * 
 * 
 */ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js') }}
		{{ javascript_include('js/utils.js') }}
        <link href='/**
 * 
 * 
 * 
 */fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>
    </head>
    <body>
	<div id="main-index">
		{{ partial('layouts/header') }}
		<div class='container'><?php $this->flashSession->output() ?></div>
        {{ content() }}
	</div>
    </body>
</html>