<div class="container">
    <h1>Latest Apps</h1>
    <ul class="app-listings">
    <?php foreach ($apps as $app) { ?>
        <li>
		<div class="icon">
        <img src=<?php echo $this->url->get($app->icon_app); ?> />
		</div>
        <h2><?php echo $app->name_app; ?></h2>
        <p><?php echo $app->tagline_app; ?></p>
        <p data-desc=<?php echo $app->desc_app; ?>></p>
        <span>Votes:</span>
        </li>
    <?php } ?>

    </ul>
</div>