<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->tag->getTitle(); ?>
        <?php echo $this->tag->stylesheetLink('css/normalize.css'); ?>
        <?php echo $this->tag->stylesheetLink('css/skeleton.css'); ?>
        
        <?php echo $this->tag->stylesheetLink('css/style.css'); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Apps.BePlace">
        <meta name="author" content="Chris Craven">
        <?php echo $this->tag->javascriptInclude('https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js'); ?>
		<?php echo $this->tag->javascriptInclude('js/utils.js'); ?>
        <link href='//fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>
    </head>
    <body>
	<div>
		<?php echo $this->partial('layouts/header'); ?>
		<div class='container'><?php $this->flashSession->output() ?></div>
        <?php echo $this->getContent(); ?>
	</div>
    </body>
</html>