

{% block content %}

<div class="container">
<?php use Phalcon\Tag; ?>
<h2>Sign up using this form</h2>
    {{ form('signup/register', 'id': 'registerForm', 'onbeforesubmit': 'return false') }}

<label for="name">First Name</label>
                {{ text_field("name", "size": "30", "class": "span6") }}
<p class="alert" id="name_alert"> Please enter your first name.</p>


<label for="email">E-Mail</label>
                {{ text_field("email", "size": "30", "class": "span6") }}
<p class="alert" id="email_alert"> Please enter a valid email.</p>


<p>
<?php echo Tag::submitButton("Register") ?>
</p>
{{ end_form() }}
</div>
{% endblock %}