
{{ content() }}

<div class="container">
<div class="row">

    <div class="col-md-6">
        <div class="page-header">
            <h2>Log In</h2>
        </div>
        {{ form('login/start', 'id': 'loginForm') }}
            
                
		<label for="email">Username/Email</label>
		
		{{ text_field('email', 'class': "form-control") }}
		<div class="alert" id="email_alert"><strong>Warning!</strong> Please enter a valid username/email.</div>
	
		<label for="password">Password</label>
		
		{{ password_field('password', 'class': "form-control") }}
		<div class="alert" id="password_alert"><strong>Warning!</strong> Please enter a valid password.</div>
	
		<div>
		{{ submit_button('Login', 'class': 'btn button-primary btn-large') }}
		</div>
                
            
        {{ end_form() }}
    </div>

    <div class="col-md-6">

        <div class="page-header">
            <h2>Don't have an account yet?</h2>
        </div>
        <p>Signing up an account offers you these benefits:</p>
        <ul>
            <li>Create your apps and promote your business online</li>
            <li>Get sponsors and bounties for you and your team</li>
            <li>Vote to earn points and get special offers on cutting-edge apps</li>
        </ul>
        <div class="clearfix">
            {{ link_to('signup', 'Sign Up', 'class': 'button button-primary btn btn-primary btn-large btn-success') }}
        </div>
    </div>
</div>
</div>